//Modules -encapsulated code (only share minimum)

const {pratik} = require('./4-names')
const sayHi = require('./5-utils')
console.log(names)
const names = require('./4-names')
const check = require('./6-alternative')
require('./7-mind-grenade')
console.log(check)
sayHi('Rutik')
sayHi(pratik)
sayHi(names.pratik)
sayHi('Kartik')